### ISSUE TITLE
Electricity does not work at Electric Growth Accelerator

### ISSUE THREAD

**Issue by hiiamken** [GuizhanCraft/GeneticChickengineering-Reborn#15]
### Checklist

- [X] You are using official version downloaded from Blob Builds (https://blob.build/) or Guizhan Builds (<https://builds.guizhanss.com>)
- [X] You checked the checksum of the downloaded file, and confirmed that the file is complete
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

![image](https://github.com/GuizhanCraft/GeneticChickengineering-Reborn/assets/142149960/1bae12bb-5004-4f5d-a1f3-e02f77eec393)
![image](https://github.com/GuizhanCraft/GeneticChickengineering-Reborn/assets/142149960/63d55ace-7ea3-4062-8140-5b942a355c48)

Electricity does not work at Electric Growth Accelerator, although there were enough materials, the animals were not large

### Reproduction Steps

1. Add enough ingredients to Electric Growth Accelerator
2. The machine is not running

### Expected Behavior

The animals should be large in theory

### Server Software

Paper

### Minecraft version

1.20.4

### Slimefun version

![image](https://github.com/GuizhanCraft/GeneticChickengineering-Reborn/assets/142149960/e8660231-40a1-4118-b17d-2bad283cb5db)
![image](https://github.com/GuizhanCraft/GeneticChickengineering-Reborn/assets/142149960/9990843c-1d99-4a9c-b655-5a8038740b20)

### Plugin version

GeneticChickengineering vBuild 9 (git 0289fc6)

**Comment by ybw0014** [comment]
this item is from core slimefun.
