### ISSUE TITLE
Spam console

### ISSUE THREAD

**Issue by hiiamken** [GuizhanCraft/GeneticChickengineering-Reborn#16]
### Checklist

- [X] You are using official version downloaded from Blob Builds (https://blob.build/) or Guizhan Builds (<https://builds.guizhanss.com>)
- [X] You checked the checksum of the downloaded file, and confirmed that the file is complete
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

My server's console is spamming like this after I adjusted the config and restarted the server

### Reproduction Steps

1. Edit config (https://controlc.com/6d683464)
2. Restart the server

### Expected Behavior

I don't want console spam anymore

### Server log

https://mclo.gs/tPhVirl

### Server Software

Paper

### Minecraft version

1.20.4

### Slimefun version

![image](https://github.com/GuizhanCraft/GeneticChickengineering-Reborn/assets/142149960/40a6ef3c-94c6-4937-a3bc-3741c50372d5)
![image](https://github.com/GuizhanCraft/GeneticChickengineering-Reborn/assets/142149960/411f5310-cf60-4824-8791-03357e11da98)
![image](https://github.com/GuizhanCraft/GeneticChickengineering-Reborn/assets/142149960/1a505c08-906b-4a76-a99d-60e2ba95c3de)
![image](https://github.com/GuizhanCraft/GeneticChickengineering-Reborn/assets/142149960/dad1c0dc-569d-4914-b01f-5e0999d5c167)

### Plugin version

vBuild 9 (git 0289fc6)

**Comment by hiiamken** [comment]
![image](https://github.com/GuizhanCraft/GeneticChickengineering-Reborn/assets/142149960/bfb130c3-3dad-451c-a3b7-fff4e02f0b83)

**Comment by hiiamken** [comment]
plugins/Slimefun/error-reports/2024-03-19-07-24 (161).err
https://controlc.com/2e799167

**Comment by ybw0014** [comment]
fixed in [b0d58c4](https://github.com/GuizhanCraft/GeneticChickengineering-Reborn/commit/b0d58c4c94be341a3fef8eb77f526b682b6f7e24)
