### ISSUE TITLE
GeneticChickengineering-Reborn + GriefPrevention conflict

### ISSUE THREAD

**Issue by SrMonsterYT** [GuizhanCraft/GeneticChickengineering-Reborn#25]
### Checklist

- [X] You are using official version downloaded from Blob Builds (https://blob.build/) or Guizhan Builds (<https://builds.guizhanss.com>)
- [X] You checked the checksum of the downloaded file, and confirmed that the file is complete
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

people manage to steal their chickens using the chicken net, here's the video a player sent me: 

video: https://www.youtube.com/watch?v=p4iP2Ox94s0 

slimefun version and addons: https://prnt.sc/rVdARgkL3k2j

### Reproduction Steps

use a chicken net to catch chickens from other land protected by GriefPrevention

### Expected Behavior

protecting the chickens

### Server Software

Other (Please specify in description)

### Minecraft version

Pufferfish git-Pufferfish-52 (MC: 1.20.4)

### Slimefun version

Slimefun Dev - 1148

### Plugin version

GeneticChickengineering-Reborn Dev - 7

**Comment by ybw0014** [comment]
good catch, it doesn't have any permission check lol
