### ISSUE TITLE
Chickens of same type do not stack

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [GuizhanCraft/GeneticChickengineering-Reborn#4]
### Checklist

- [X] You are using official version downloaded from Builds Page
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

NBT data - https://paste.gg/p/anonymous/957e7d05f26940d4bc2b476694b07135

Images - https://discord.com/channels/809178621424041997/1171887356396191785/1175318003496271953

And

https://discord.com/channels/809178621424041997/1171887356396191785/1175332032260358154

### Reproduction Steps

1. Breed chicken
2. Try to stack them

### Expected Behavior

Should stack

### Server log

N/A

### Error report

N/A

### Server Software

Purpur

### Minecraft Version

Below

### Slimefun version

This Server uses the following setup of Slimefun:
Purpur git-Purpur-2077 (MC: 1.20.2)
Slimefun DEV - 1104 (git c977454e)
Metrics-Module #29
Java 18
Installed Addons: (18)
Networks vDEV - 50 (git 3de3c9d6)
CrystamaeHistoria vDEV - 81 (git 0c0efa95)
Gastronomicon vDEV - 8 (git 76336191)
FastMachines vBuild 9 (git 00f7d11)
FoxyMachines vDEV - 67 (git 0028aa93)
Quaptics vDEV - 4 (git cbc2e78e)
SlimeTech v3.0.0
SFAdvancements vDEV - 25 (git 661a326b)
HeadLimiter vDEV - 15 (git 66d18f52)
SlimeHUD vDEV - 11 (git b6dc2d53)
SFCalc vDEV - 37 (git dfc0fc41)
LiteXpansion vDEV - 192 (git 661862ed)
DracFun v1.0.0
MobCapturer vDEV - 33 (git 6fc26c35)
SpiritsUnchained vDEV - 22 (git 28e031e0)
TranscEndence vDEV - 41 (git 98d7d47e)
FluffyMachines vDEV - 132 (git ccf029ba)
GeneticChickengineering vBuild 2 (git dbbd7a9)

### Plugin version

Above

**Comment by ybw0014** [comment]
This is intended. The chicken capturing is the same as MobCapturer, it keeps most attributes of chickens. Chickens will have different modifiers that do not show in the lore.
