### ISSUE TITLE
Skip baby stage for chicken

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [GuizhanCraft/GeneticChickengineering-Reborn#5]
### Checklist

- [X] You are using official version downloaded from Builds Page
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

Images - https://discord.com/channels/809178621424041997/1171887356396191785/1175335708639121418

### Reproduction Steps

1. Breed to get a baby chicken
2. Place the baby chicken egg [player head] and you get a FULL grown chicken
3. Capture it with net and you dont have to wait for it to grow

### Expected Behavior

Should spawn baby

### Server log

N/A

### Error report

N/A

### Server Software

Purpur

### Minecraft Version

Below 

### Slimefun version

This Server uses the following setup of Slimefun:
Purpur git-Purpur-2077 (MC: 1.20.2)
Slimefun DEV - 1104 (git c977454e)
Metrics-Module #29
Java 18
Installed Addons: (18)
Networks vDEV - 50 (git 3de3c9d6)
CrystamaeHistoria vDEV - 81 (git 0c0efa95)
Gastronomicon vDEV - 8 (git 76336191)
FastMachines vBuild 9 (git 00f7d11)
FoxyMachines vDEV - 67 (git 0028aa93)
Quaptics vDEV - 4 (git cbc2e78e)
SlimeTech v3.0.0
SFAdvancements vDEV - 25 (git 661a326b)
HeadLimiter vDEV - 15 (git 66d18f52)
SlimeHUD vDEV - 11 (git b6dc2d53)
SFCalc vDEV - 37 (git dfc0fc41)
LiteXpansion vDEV - 192 (git 661862ed)
DracFun v1.0.0
MobCapturer vDEV - 33 (git 6fc26c35)
SpiritsUnchained vDEV - 22 (git 28e031e0)
TranscEndence vDEV - 41 (git 98d7d47e)
FluffyMachines vDEV - 132 (git ccf029ba)
GeneticChickengineering vBuild 2 (git dbbd7a9)

### Plugin version

Above

**Comment by ybw0014** [comment]
will be fixed in next patch

**Comment by ybw0014** [comment]
https://github.com/GuizhanCraft/GeneticChickengineering-Reborn/commit/def067f4920a3d4d5c98e4f9ca5e5c13f7ba315f
