### ISSUE TITLE
Excitation and Restoration chamber don't have status bar

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [GuizhanCraft/GeneticChickengineering-Reborn#6]
### Checklist

- [X] You are using official version downloaded from Builds Page
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

Images -
https://discord.com/channels/809178621424041997/1171887356396191785/1175342536294940762

https://discord.com/channels/809178621424041997/1171887356396191785/1175347208539881583

### Reproduction Steps

Place any of the chambers and put an adult chicken inside

### Expected Behavior

Have a status bar

### Server log

N/A

### Error report

N/A

### Server Software

Purpur

### Minecraft Version

Below

### Slimefun version

This Server uses the following setup of Slimefun:
Purpur git-Purpur-2077 (MC: 1.20.2)
Slimefun DEV - 1104 (git c977454e)
Metrics-Module #29
Java 18
Installed Addons: (18)
Networks vDEV - 50 (git 3de3c9d6)
CrystamaeHistoria vDEV - 81 (git 0c0efa95)
Gastronomicon vDEV - 8 (git 76336191)
FastMachines vBuild 9 (git 00f7d11)
FoxyMachines vDEV - 67 (git 0028aa93)
Quaptics vDEV - 4 (git cbc2e78e)
SlimeTech v3.0.0
SFAdvancements vDEV - 25 (git 661a326b)
HeadLimiter vDEV - 15 (git 66d18f52)
SlimeHUD vDEV - 11 (git b6dc2d53)
SFCalc vDEV - 37 (git dfc0fc41)
LiteXpansion vDEV - 192 (git 661862ed)
DracFun v1.0.0
MobCapturer vDEV - 33 (git 6fc26c35)
SpiritsUnchained vDEV - 22 (git 28e031e0)
TranscEndence vDEV - 41 (git 98d7d47e)
FluffyMachines vDEV - 132 (git ccf029ba)
GeneticChickengineering vBuild 2 (git https://github.com/GuizhanCraft/GeneticChickengineering-Reborn/commit/dbbd7a9d34a38686d0ac8883c28a0e1fe97c3321)

### Plugin version

Above

**Comment by ybw0014** [comment]
will be fixed in next patch

**Comment by ybw0014** [comment]
https://github.com/GuizhanCraft/GeneticChickengineering-Reborn/commit/898a759f53cc936aeb9aa3ccc7e7d8a41bc9b893
